### ISSUE TITLE
segfault on download

### ISSUE THREAD

**Issue by jjlawren** [aria2/aria2#1138]
I'm using a packaged version provided with SmartOS:
```
aria2 version 1.32.0

** Configuration **
Enabled Features: Async DNS, BitTorrent, Firefox3 Cookie, GZip, HTTPS, Message Digest, Metalink, XML-RPC
Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32
Libraries: zlib/1.2.11 expat/2.2.4 sqlite3/3.21.0 OpenSSL/1.0.2n c-ares/1.13.0
Compiler: gcc 4.9.4
  built by   x86_64-sun-solaris2.11
  on         Dec 31 2017 02:45:51
System: Unknown system
```

When launching with an HTTPS URL and default options, it segfaults immediately when attemping to connect to the host:
```
...
02/14 13:46:27 [NOTICE] Downloading 1 item(s)
02/14 13:46:27 [INFO] System trusted CA certificates were successfully added.
02/14 13:46:27 [DEBUG] 1 RequestGroup(s) added.
02/14 13:46:27 [DEBUG] nget=0
02/14 13:46:27 [DEBUG] CUID#7 - socket: read:0, write:0, hup:0, err:0
02/14 13:46:27 [DEBUG] Selected from normCands
02/14 13:46:27 [DEBUG] FeedbackURISelector selected https://username:password@my.hostname.com/files/recipes.txt
02/14 13:46:27 [DEBUG] nget=0
02/14 13:46:27 [DEBUG] CUID#7 - socket: read:0, write:0, hup:0, err:0
02/14 13:46:27 [INFO] CUID#7 - Connecting to my.hostname.com:443
Segmentation Fault (core dumped)
```
backtrace:
```
#0  0x00000000006078a5 in std::string::_Rep::_M_dispose(std::allocator<char> const&) [clone .part.7] ()
#1  0x000000000060c089 in aria2::SocketCore::establishConnection(std::string const&, unsigned short, bool) ()
#2  0x00000000007ab6d3 in aria2::HttpInitiateConnectionCommand::createNextCommand(std::string const&, std::string const&, unsigned short, std::vector<std::string, std::allocator<std::string> > const&, std::shared_ptr<aria2::Request> const&) ()
#3  0x00000000007cac9a in aria2::InitiateConnectionCommand::executeInternal() ()
#4  0x0000000000791feb in aria2::AbstractCommand::execute() ()
#5  0x00000000006c3f66 in aria2::(anonymous namespace)::executeCommand(std::deque<std::unique_ptr<aria2::Command, std::default_delete<aria2::Command> >, std::allocator<std::unique_ptr<aria2::Command, std::default_delete<aria2::Command> > > >&, aria2::Command::STATUS) ()
#6  0x00000000006c40ff in aria2::DownloadEngine::run(bool) ()
#7  0x00000000005b86fb in aria2::MultiUrlRequestInfo::execute() ()
#8  0x0000000000827e5c in aria2::main(int, char**) ()
#9  0x0000000000827ee9 in main ()
```

**Comment by jjlawren** [comment]
This was an issue in the packaged version, resolved in SmartOS pkgsrc 2018Q2 and later.
