### ISSUE TITLE
JSON-RPC urllib2.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by iG8R** [aria2/aria2#1235]
Hi.
I faced with some weird issue.

Here is my test Python script:
```
#!/usr/bin/env python2

import json, urllib2, sys, os
from argparse import ArgumentParser
from collections import defaultdict

jsonreq = json.dumps({'jsonrpc':'2.0', 'id':'qwer', 'method':'aria2.addUri', 'params':
[['https://cs640506.vkuservideo.net/5/u5879182/videos/1f08873a1a.1080.mp4'],
{'max-connection-per-server': 15, 'rpc-user': 'user', 'rpc-passwd': 'password',
'min-split-size': '10M', 'user-agent': 'Mozilla/5.0 (X11; Linux; rv:5.0) Gecko/5.0 Firefox/5.0',
'continue': 'true', 'split': 15}]})

print urllib2.urlopen('http://192.168.0.5:6800/jsonrpc/', jsonreq).read()
```

As a result I receive:
```
f:\aria2rpc_test.py
Traceback (most recent call last):
  File "F:\_Downloads\Aria2 (Torrent & Downloader)\aria2rpc-master\aria2rpc_test.py", line 9, in <module>
    print urllib2.urlopen('http://192.168.0.5:6800/jsonrpc/', jsonreq).read()
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

There is following in Aria2.log:
```
2018-07-07 23:35:44.994598 [INFO] [AbstractHttpServerResponseCommand.cc:118] CUID#11 - HttpServer: all response transmitted.
2018-07-07 23:36:33.227762 [INFO] [HttpListenCommand.cc:78] RPC: Accepted the connection from 192.168.0.3:65364.
2018-07-07 23:36:33.228807 [INFO] [HttpServer.cc:187] HTTP Server received request
POST /jsonrpc/ HTTP/1.1
Accept-Encoding: identity
Content-Length: 370
Host: 192.168.0.5:6800
Content-Type: application/x-www-form-urlencoded
Connection: close
User-Agent: Python-urllib/2.7

2018-07-07 23:36:33.228807 [INFO] [HttpServer.cc:191] Request path is invalid. Ignore the request body.
2018-07-07 23:36:33.228807 [DEBUG] [HttpServer.cc:296] HTTP Server sends response:
HTTP/1.1 401 Unauthorized
Date: Sat, 07 Jul 2018 20:36:33 GMT
Content-Length: 0
Expires: Sat, 07 Jul 2018 20:36:33 GMT
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Connection: close
WWW-Authenticate: Basic realm="aria2"
```

Could someone explain why I'm not able to pass through the authorization?
I'll very appreciate your help.

**Comment by iG8R** [comment]
This issue was solved - just used "token" instead of "user/password" for the authorization.
