### ISSUE TITLE
Segv in v1.35.0 test suite

### ISSUE THREAD

**Issue by mgorny** [aria2/aria2#1476]
I've just attempted building 1.35.0 and the tests segfault for me.

Backtrace:
```
#0  __GI___libc_free (mem=0x100000affff0000) at malloc.c:3111
#1  0x000055dad99a481d in std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (
    __pointer=0x55dadadd5470) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:98
#2  0x000055dad99a3e65 in std::_Destroy_aux<false>::__destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*> (
    __first=0x55dadadd5470, __last=0x55dadadd5430) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:108
#3  0x000055dad99a3148 in std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*> (
    __first=0x55dadadd5450, __last=0x55dadadd5430) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:137
#4  0x000055dad99a1e59 in std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__first=0x55dadadd5450, __last=0x55dadadd5430)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:206
#5  0x000055dad99ce5e5 in std::deque<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_destroy_data_aux (this=0x7ffc06d5dcb8, 
    __first=<error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>, 
    __last="Expression: memcmp(&ans, &dest, sizeof(ans)) == 0") at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/deque.tcc:870
#6  0x00007f1e7b1ed4d1 in CppUnit::Message::~Message() () from /usr/lib64/libcppunit-1.14.so.0
#7  0x000055dad99a7c09 in aria2::SocketCoreTest::testInetPton (this=0x55dadad71430) at SocketCoreTest.cc:128
#8  0x000055dad99aef52 in std::__invoke_impl<void, void (aria2::SocketCoreTest::*&)(), aria2::SocketCoreTest*&> (
    __f=@0x55dadad71370: (void (aria2::SocketCoreTest::*)(class aria2::SocketCoreTest * const)) 0x55dad99a785c <aria2::SocketCoreTest::testInetPton()>, __t=@0x55dadad71380: 0x55dadad71430) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/invoke.h:73
#9  0x000055dad99aeda4 in std::__invoke<void (aria2::SocketCoreTest::*&)(), aria2::SocketCoreTest*&> (
    __fn=@0x55dadad71370: (void (aria2::SocketCoreTest::*)(class aria2::SocketCoreTest * const)) 0x55dad99a785c <aria2::SocketCoreTest::testInetPton()>, __args#0=@0x55dadad71380: 0x55dadad71430) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/invoke.h:95
#10 0x000055dad99ae903 in std::_Bind<void (aria2::SocketCoreTest::*(aria2::SocketCoreTest*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x55dadad71370, __args=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/functional:400
#11 0x000055dad99ae3a1 in std::_Bind<void (aria2::SocketCoreTest::*(aria2::SocketCoreTest*))()>::operator()<, void>() (this=0x55dadad71370)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/functional:484
#12 0x000055dad99ad821 in std::_Function_handler<void (), std::_Bind<void (aria2::SocketCoreTest::*(aria2::SocketCoreTest*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/std_function.h:300
#13 0x000055dad99af30e in std::function<void ()>::operator()() const (this=0x55dadad88310)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/std_function.h:690
#14 0x000055dad99af22e in CppUnit::TestCaller<aria2::SocketCoreTest>::runTest (this=0x55dadad882d0) at /usr/include/cppunit/TestCaller.h:175
#15 0x00007f1e7b1f5a52 in CppUnit::TestCaseMethodFunctor::operator()() const () from /usr/lib64/libcppunit-1.14.so.0
#16 0x00007f1e7b1ebb27 in CppUnit::DefaultProtector::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) ()
   from /usr/lib64/libcppunit-1.14.so.0
#17 0x00007f1e7b1f2add in CppUnit::ProtectorChain::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) ()
   from /usr/lib64/libcppunit-1.14.so.0
#18 0x00007f1e7b1fb960 in CppUnit::TestResult::protect(CppUnit::Functor const&, CppUnit::Test*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libcppunit-1.14.so.0
#19 0x00007f1e7b1f5867 in CppUnit::TestCase::run(CppUnit::TestResult*) () from /usr/lib64/libcppunit-1.14.so.0
#20 0x00007f1e7b1f5d92 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) () from /usr/lib64/libcppunit-1.14.so.0
#21 0x00007f1e7b1f5ca6 in CppUnit::TestComposite::run(CppUnit::TestResult*) () from /usr/lib64/libcppunit-1.14.so.0
#22 0x00007f1e7b1f5d92 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) () from /usr/lib64/libcppunit-1.14.so.0
#23 0x00007f1e7b1f5ca6 in CppUnit::TestComposite::run(CppUnit::TestResult*) () from /usr/lib64/libcppunit-1.14.so.0
#24 0x00007f1e7b1fb86a in CppUnit::TestResult::runTest(CppUnit::Test*) () from /usr/lib64/libcppunit-1.14.so.0
#25 0x00007f1e7b1fe38e in CppUnit::TestRunner::run(CppUnit::TestResult&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libcppunit-1.14.so.0
#26 0x00007f1e7b1fff54 in CppUnit::TextTestRunner::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, bool) () from /usr/lib64/libcppunit-1.14.so.0
#27 0x000055dad999f49b in main (argc=1, argv=0x7ffc06d5e4b8) at AllTest.cc:50

```

Build log: [net-misc:aria2-1.35.0:20191006-074955.log](https://github.com/aria2/aria2/files/3694127/net-misc.aria2-1.35.0.20191006-074955.log)

**Comment by tatsuhiro-t** [comment]
It happens with debian packaged cppunit.  Compiling cppunit yourself will fix it.  I don't know exactly why this happens.

**Comment by mgorny** [comment]
I'm using Gentoo, so I've built cppunit on my machine. FWICS that's vanilla cppunit 1.14.0 with no patches or anything special about the build.

**Comment by tatsuhiro-t** [comment]
I've tried cppunit 1.14.0 and latest master, compiled by myself, and all worked fine.
Downgrading cppunit 1.13.x might work.

**Comment by SKIYET** [comment]
I use debian with tcmalloc instead of malloc，it is ok.

**Comment by mgorny** [comment]
I'm going to rebuild cppunit with debug symbols and try to investigate.

**Comment by mgorny** [comment]
After adding more debug symbols, this looks entirely like a fault in aria2's memory management:

```
#0  __GI___libc_free (mem=0xc2f9ef642b88c800) at malloc.c:3111
#1  0x0000555555738a76 in std::_Destroy<aria2::URIResult> (__pointer=0x7fffffffca58)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:98
#2  0x0000555555738389 in std::_Destroy_aux<false>::__destroy<aria2::URIResult*> (__first=0x7fffffffca58, __last=0x7fffffffcb40)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:108
#3  0x0000555555737892 in std::_Destroy<aria2::URIResult*> (__first=0x7fffffffca30, __last=0x7fffffffcb40)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:137
#4  0x00005555557366dc in std::_Destroy<aria2::URIResult*, aria2::URIResult> (__first=0x7fffffffca30, __last=0x7fffffffcb40)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:206
#5  0x0000555555734de6 in std::deque<aria2::URIResult, std::allocator<aria2::URIResult> >::_M_destroy_data_aux (this=0x7fffffffce30, __first=
  {uri_ = "\000\000\000\000\000\000\000\000\020@\342UUU\000\000\023\000\000\000\000\000\000\000Ki8KLyoK\002\000\000\000YXJp\340\313\352UUU\000\000\024\000\000\000\000\000\000\000\024\000\000\000\000\000\000\000ZCBkb3du\002\000\000\000ZCB1\000\314\352UUU\000\000\024\000\000\000\000\000\000\000\024\000\000\000\000\000\000\000aWdodCAo\000\000\000\000MjAw`\343\352UUU\000\000\030\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000YXdhCiAq\001\000\000\000IFRoaXMgcHJvZ3JhbSBpcyBmcmVlIHNvZnR3YXJlOyB5"..., result_ = aria2::error_code::FINISHED}, 
    __last=non-dereferenceable iterator for std::deque) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/deque.tcc:864
#6  0x00007ffff7d4f7d9 in std::deque<aria2::URIResult, std::allocator<aria2::URIResult> >::_M_erase(std::_Deque_iterator<aria2::URIResult, aria2::URIResult&, aria2::URIResult*>, std::_Deque_iterator<aria2::URIResult, aria2::URIResult&, aria2::URIResult*>) () from /usr/lib64/libaria2.so.0
#7  0x00007ffff7d4a1b6 in aria2::FileEntry::extractURIResult(std::deque<aria2::URIResult, std::allocator<aria2::URIResult> >&, aria2::error_code::Value) () from /usr/lib64/libaria2.so.0
#8  0x0000555555726518 in aria2::FileEntryTest::testExtractURIResult (this=0x555555e4af90) at FileEntryTest.cc:75
#9  0x00005555557388c2 in std::__invoke_impl<void, void (aria2::FileEntryTest::*&)(), aria2::FileEntryTest*&> (
    __f=@0x555555e4aa50: (void (aria2::FileEntryTest::*)(aria2::FileEntryTest * const)) 0x55555572631a <aria2::FileEntryTest::testExtractURIResult()>, __t=@0x555555e4aa60: 0x555555e4af90) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/invoke.h:73
#10 0x0000555555738062 in std::__invoke<void (aria2::FileEntryTest::*&)(), aria2::FileEntryTest*&> (
    __fn=@0x555555e4aa50: (void (aria2::FileEntryTest::*)(aria2::FileEntryTest * const)) 0x55555572631a <aria2::FileEntryTest::testExtractURIResult()>, __args#0=@0x555555e4aa60: 0x555555e4af90) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/invoke.h:95
#11 0x000055555573756f in std::_Bind<void (aria2::FileEntryTest::*(aria2::FileEntryTest*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x555555e4aa50, __args=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/functional:400
#12 0x00005555557362bd in std::_Bind<void (aria2::FileEntryTest::*(aria2::FileEntryTest*))()>::operator()<, void>() (this=0x555555e4aa50)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/functional:484
#13 0x0000555555734747 in std::_Function_handler<void (), std::_Bind<void (aria2::FileEntryTest::*(aria2::FileEntryTest*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/std_function.h:300
#14 0x000055555571530e in std::function<void ()>::operator()() const (this=0x555555e60ec0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/std_function.h:690
#15 0x000055555573965e in CppUnit::TestCaller<aria2::FileEntryTest>::runTest (this=0x555555e60e80) at /usr/include/cppunit/TestCaller.h:175
#16 0x00007ffff7b45a24 in CppUnit::TestCaseMethodFunctor::operator() (this=0x7fffffffd3c0)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestCase.cpp:32
#17 0x00007ffff7b364cf in CppUnit::DefaultProtector::protect (this=0x555555eab280, functor=..., context=...)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/DefaultProtector.cpp:15
#18 0x00007ffff7b3fb1f in CppUnit::ProtectorChain::ProtectFunctor::operator() (this=0x555555eae4c0)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/ProtectorChain.cpp:20
#19 0x00007ffff7b3f9ab in CppUnit::ProtectorChain::protect (this=0x555555eaa3c0, functor=..., context=...)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/ProtectorChain.cpp:86
#20 0x00007ffff7b50e01 in CppUnit::TestResult::protect (this=0x555555e7dc40, functor=..., test=0x555555e60e80, shortDescription="")
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestResult.cpp:182
#21 0x00007ffff7b454c5 in CppUnit::TestCase::run (this=0x555555e60e80, result=0x555555e7dc40)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestCase.cpp:91
#22 0x00007ffff7b460aa in CppUnit::TestComposite::doRunChildTests (this=0x555555e60d80, controller=0x555555e7dc40)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:64
#23 0x00007ffff7b45f2c in CppUnit::TestComposite::run (this=0x555555e60d80, result=0x555555e7dc40)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:23
#24 0x00007ffff7b460aa in CppUnit::TestComposite::doRunChildTests (this=0x555555e5ff30, controller=0x555555e7dc40)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:64
#25 0x00007ffff7b45f2c in CppUnit::TestComposite::run (this=0x555555e5ff30, result=0x555555e7dc40)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:23
#26 0x00007ffff7b5513c in CppUnit::TestRunner::WrappingSuite::run (this=0x555555eaa7c0, result=0x555555e7dc40)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestRunner.cpp:47
#27 0x00007ffff7b50b82 in CppUnit::TestResult::runTest (this=0x555555e7dc40, test=0x555555eaa7c0)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestResult.cpp:149
#28 0x00007ffff7b553b3 in CppUnit::TestRunner::run (this=0x7fffffffd6a0, controller=..., testPath="")
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestRunner.cpp:96
#29 0x00007ffff7b5927b in CppUnit::TextTestRunner::run (this=0x7fffffffd6a0, controller=..., testPath="")
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TextTestRunner.cpp:140
#30 0x00007ffff7b59087 in CppUnit::TextTestRunner::run (this=0x7fffffffd6a0, testName="", doWait=false, doPrintResult=true, doPrintProgress=true)
    at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TextTestRunner.cpp:64
#31 0x000055555570549b in main (argc=1, argv=0x7fffffffd7f8) at AllTest.cc:50

**Comment by arlllk** [comment]
In Arch using 

> gcc version 9.2.0 (GCC)
> cppunit 1.14.0

Also happens segfault
Also tried whit jemalloc and tcmalloc, and the problem doesn't get it fixed

**Comment by SKIYET** [comment]
> 
> 
> After adding more debug symbols, this looks entirely like a fault in aria2's memory management:
> 
> ```
> #0  __GI___libc_free (mem=0xc2f9ef642b88c800) at malloc.c:3111
> #1  0x0000555555738a76 in std::_Destroy<aria2::URIResult> (__pointer=0x7fffffffca58)
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:98
> #2  0x0000555555738389 in std::_Destroy_aux<false>::__destroy<aria2::URIResult*> (__first=0x7fffffffca58, __last=0x7fffffffcb40)
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:108
> #3  0x0000555555737892 in std::_Destroy<aria2::URIResult*> (__first=0x7fffffffca30, __last=0x7fffffffcb40)
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:137
> #4  0x00005555557366dc in std::_Destroy<aria2::URIResult*, aria2::URIResult> (__first=0x7fffffffca30, __last=0x7fffffffcb40)
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/stl_construct.h:206
> #5  0x0000555555734de6 in std::deque<aria2::URIResult, std::allocator<aria2::URIResult> >::_M_destroy_data_aux (this=0x7fffffffce30, __first=
>   {uri_ = "\000\000\000\000\000\000\000\000\020@\342UUU\000\000\023\000\000\000\000\000\000\000Ki8KLyoK\002\000\000\000YXJp\340\313\352UUU\000\000\024\000\000\000\000\000\000\000\024\000\000\000\000\000\000\000ZCBkb3du\002\000\000\000ZCB1\000\314\352UUU\000\000\024\000\000\000\000\000\000\000\024\000\000\000\000\000\000\000aWdodCAo\000\000\000\000MjAw`\343\352UUU\000\000\030\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000YXdhCiAq\001\000\000\000IFRoaXMgcHJvZ3JhbSBpcyBmcmVlIHNvZnR3YXJlOyB5"..., result_ = aria2::error_code::FINISHED}, 
>     __last=non-dereferenceable iterator for std::deque) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/deque.tcc:864
> #6  0x00007ffff7d4f7d9 in std::deque<aria2::URIResult, std::allocator<aria2::URIResult> >::_M_erase(std::_Deque_iterator<aria2::URIResult, aria2::URIResult&, aria2::URIResult*>, std::_Deque_iterator<aria2::URIResult, aria2::URIResult&, aria2::URIResult*>) () from /usr/lib64/libaria2.so.0
> #7  0x00007ffff7d4a1b6 in aria2::FileEntry::extractURIResult(std::deque<aria2::URIResult, std::allocator<aria2::URIResult> >&, aria2::error_code::Value) () from /usr/lib64/libaria2.so.0
> #8  0x0000555555726518 in aria2::FileEntryTest::testExtractURIResult (this=0x555555e4af90) at FileEntryTest.cc:75
> #9  0x00005555557388c2 in std::__invoke_impl<void, void (aria2::FileEntryTest::*&)(), aria2::FileEntryTest*&> (
>     __f=@0x555555e4aa50: (void (aria2::FileEntryTest::*)(aria2::FileEntryTest * const)) 0x55555572631a <aria2::FileEntryTest::testExtractURIResult()>, __t=@0x555555e4aa60: 0x555555e4af90) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/invoke.h:73
> #10 0x0000555555738062 in std::__invoke<void (aria2::FileEntryTest::*&)(), aria2::FileEntryTest*&> (
>     __fn=@0x555555e4aa50: (void (aria2::FileEntryTest::*)(aria2::FileEntryTest * const)) 0x55555572631a <aria2::FileEntryTest::testExtractURIResult()>, __args#0=@0x555555e4aa60: 0x555555e4af90) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/invoke.h:95
> #11 0x000055555573756f in std::_Bind<void (aria2::FileEntryTest::*(aria2::FileEntryTest*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x555555e4aa50, __args=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/functional:400
> #12 0x00005555557362bd in std::_Bind<void (aria2::FileEntryTest::*(aria2::FileEntryTest*))()>::operator()<, void>() (this=0x555555e4aa50)
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/functional:484
> #13 0x0000555555734747 in std::_Function_handler<void (), std::_Bind<void (aria2::FileEntryTest::*(aria2::FileEntryTest*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/std_function.h:300
> #14 0x000055555571530e in std::function<void ()>::operator()() const (this=0x555555e60ec0)
>     at /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/bits/std_function.h:690
> #15 0x000055555573965e in CppUnit::TestCaller<aria2::FileEntryTest>::runTest (this=0x555555e60e80) at /usr/include/cppunit/TestCaller.h:175
> #16 0x00007ffff7b45a24 in CppUnit::TestCaseMethodFunctor::operator() (this=0x7fffffffd3c0)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestCase.cpp:32
> #17 0x00007ffff7b364cf in CppUnit::DefaultProtector::protect (this=0x555555eab280, functor=..., context=...)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/DefaultProtector.cpp:15
> #18 0x00007ffff7b3fb1f in CppUnit::ProtectorChain::ProtectFunctor::operator() (this=0x555555eae4c0)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/ProtectorChain.cpp:20
> #19 0x00007ffff7b3f9ab in CppUnit::ProtectorChain::protect (this=0x555555eaa3c0, functor=..., context=...)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/ProtectorChain.cpp:86
> #20 0x00007ffff7b50e01 in CppUnit::TestResult::protect (this=0x555555e7dc40, functor=..., test=0x555555e60e80, shortDescription="")
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestResult.cpp:182
> #21 0x00007ffff7b454c5 in CppUnit::TestCase::run (this=0x555555e60e80, result=0x555555e7dc40)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestCase.cpp:91
> #22 0x00007ffff7b460aa in CppUnit::TestComposite::doRunChildTests (this=0x555555e60d80, controller=0x555555e7dc40)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:64
> #23 0x00007ffff7b45f2c in CppUnit::TestComposite::run (this=0x555555e60d80, result=0x555555e7dc40)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:23
> #24 0x00007ffff7b460aa in CppUnit::TestComposite::doRunChildTests (this=0x555555e5ff30, controller=0x555555e7dc40)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:64
> #25 0x00007ffff7b45f2c in CppUnit::TestComposite::run (this=0x555555e5ff30, result=0x555555e7dc40)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestComposite.cpp:23
> #26 0x00007ffff7b5513c in CppUnit::TestRunner::WrappingSuite::run (this=0x555555eaa7c0, result=0x555555e7dc40)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestRunner.cpp:47
> #27 0x00007ffff7b50b82 in CppUnit::TestResult::runTest (this=0x555555e7dc40, test=0x555555eaa7c0)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestResult.cpp:149
> #28 0x00007ffff7b553b3 in CppUnit::TestRunner::run (this=0x7fffffffd6a0, controller=..., testPath="")
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TestRunner.cpp:96
> #29 0x00007ffff7b5927b in CppUnit::TextTestRunner::run (this=0x7fffffffd6a0, controller=..., testPath="")
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TextTestRunner.cpp:140
> #30 0x00007ffff7b59087 in CppUnit::TextTestRunner::run (this=0x7fffffffd6a0, testName="", doWait=false, doPrintResult=true, doPrintProgress=true)
>     at /usr/src/debug/dev-util/cppunit-1.14.0/cppunit-1.14.0/src/cppunit/TextTestRunner.cpp:64
> #31 0x000055555570549b in main (argc=1, argv=0x7fffffffd7f8) at AllTest.cc:50
> ```
These 

> 
> 
> In Arch using
> 
> > gcc version 9.2.0 (GCC)
> > cppunit 1.14.0
> 
> Also happens segfault
> Also tried whit jemalloc and tcmalloc, and the problem doesn't get it fixed

Your tcmalloc linked to aria2?

**Comment by arlllk** [comment]
@SKIYET I change the config arguments before build, did a clean build and then use the config arguments to use tcmalloc and jemalloc in each case, and always failed in the same test

**Comment by SKIYET** [comment]
> 
> 
> @SKIYET I change the config arguments before build, did a clean build and then use the config arguments to use tcmalloc and jemalloc in each case, and always failed in the same test

I make a static build ，maybe this is the reason.

**Comment by arlllk** [comment]
> I make a static build ，maybe this is the reason.

Just builded with:

```
./configure \
--prefix=/usr \
--enable-libaria2 \ 
--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt \
--enable-static \ 
--disable-shared
```

As reported from configure
```
Host type:      x86_64-pc-linux-gnu
    Install prefix: /usr
    C compiler:     gcc
    CFlags:         -march=native -mtune=native -O2 -pipe -fno-plt
    Library types:  Shared=no, Static=yes
    CUnit:          yes
    Nettle:         yes
    Build examples: yes
```
The same test fails.

I'm gonna try without all optimizations

**Comment by tatsuhiro-t** [comment]
I don't see any issues with aria2 code.

**Comment by SKIYET** [comment]
> 
> 
> I don't see any issues with aria2 code.

I use apt to install cppunit....
And my system is Debian sid.

**Comment by ObserverOfTime** [comment]
Same issue here. Probably related to #1450 & #1429.

**Comment by mgorny** [comment]
Hmm, it seems that it stopped segfaulting for me for some reason.
