### ISSUE TITLE
SIGPIPE in ::aria2::GnuTLSSession::closeConnection

### ISSUE THREAD

**Issue by stepanbujnak** [aria2/aria2#777]
I encountered SIGPIPE while running a program using libaria2 with the following GDB backtrace:

```Thread 5 "downloader" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fffe7c67700 (LWP 10292)]
0x00007ffff5cd940d in writev () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff5cd940d in writev () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4d80f69 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#2  0x00007ffff4d7ba31 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#3  0x00007ffff4d9dd18 in gnutls_alert_send () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#4  0x00007ffff4d7d829 in gnutls_bye () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#5  0x00007ffff75c6e92 in aria2::GnuTLSSession::closeConnection (this=0xe90500) at ../../src/src/LibgnutlsTLSSession.cc:178
#6  0x00007ffff759dd18 in aria2::SocketCore::closeConnection (this=this@entry=0xe79290) at ../../src/src/SocketCore.cc:638
#7  0x00007ffff759ddc9 in aria2::SocketCore::~SocketCore (this=0xe79290, __in_chrg=<optimized out>) at ../../src/src/SocketCore.cc:176
#8  0x00007ffff74a7cb9 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0xe79280) at /usr/include/c++/5/bits/shared_ptr_base.h:150
#9  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x18f21d0, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:659
#10 std::__shared_ptr<aria2::SocketCore, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x18f21c8, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr_base.h:925
#11 std::shared_ptr<aria2::SocketCore>::~shared_ptr (this=0x18f21c8, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/shared_ptr.h:93
#12 aria2::AbstractCommand::~AbstractCommand (this=0x18f2190, __in_chrg=<optimized out>) at ../../src/src/AbstractCommand.cc:113
#13 0x00007ffff752a519 in aria2::HttpResponseCommand::~HttpResponseCommand (this=0x18f2190, __in_chrg=<optimized out>) at ../../src/src/HttpResponseCommand.h:60
#14 0x00007ffff74e5f29 in std::default_delete<aria2::Command>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:76
#15 std::unique_ptr<aria2::Command, std::default_delete<aria2::Command> >::reset (__p=<optimized out>, this=0x7fffe7c66c30) at /usr/include/c++/5/bits/unique_ptr.h:344
#16 aria2::(anonymous namespace)::executeCommand (commands=std::deque with 4597 elements = {...}, statusFilter=statusFilter@entry=aria2::Command::STATUS_ACTIVE) at ../../src/src/DownloadEngine.cc:140
#17 0x00007ffff74e60aa in aria2::DownloadEngine::run (this=0x955fb0, oneshot=true) at ../../src/src/DownloadEngine.cc:175
#18 0x00007ffff767e990 in aria2::run (session=<optimized out>, mode=mode@entry=aria2::RUN_ONCE) at ../../src/src/aria2api.cc:157
```

What could be the possible cause? Is it safe to ignore the signal with `signal(SIGPIPE, SIG_IGN);`?

**Comment by tatsuhiro-t** [comment]
I think almost all network applications ignore SIGPIPE.
