### ISSUE TITLE
aria2.saveSession method does not exist

### ISSUE THREAD

**Issue by RicterZ** [aria2/aria2#778]
aria2c version 1.29.0

Refer to document: https://aria2.github.io/manual/en/html/aria2c.html#aria2.saveSession but in fact the method is not exist.

    Traceback (most recent call last):
      File "aria2_session.py", line 33, in <module>
        main()
      File "aria2_session.py", line 31, in main
        pprint(s.aria2.saveSession())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
        return self.__send(self.__name, args)
      File "aria2_session.py", line 19, in __request
        return ServerProxy._ServerProxy__request(self, methodname, params)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
        verbose=self.__verbose
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
        return self.single_request(host, handler, request_body, verbose)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1313, in single_request
        return self.parse_response(response)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1490, in parse_response
        return u.close()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 799, in close
        raise Fault(**self._stack[0])
    xmlrpclib.Fault: <Fault 1: 'No such method: aria2.saveSession'>

**Comment by RicterZ** [comment]
New aria2c binary not be installed. Closed.
